### ISSUE TITLE
normalize waitForJS var name

### ISSUE THREAD

**Issue by bjrmatos** [jsreport/jsreport-phantom-pdf#1]
while developing `jsreport-electron-pdf` i noticed that probably is best to standardize the name of `waitForJS` var name across recipes to something more generic for the `jsreport` use case.

in `jsreport-phantom-pdf` and `jsreport-phantom-image` the var name is `PHANTOM_HTML_TO_PDF_READY `, while `PHANTOM_HTML_TO_PDF_READY ` makes sense in the case of `phantom-html-to-pdf` but in `jsreport` would be more convenient to set this name equally (at least in the repositories that we maintain), so in [`jsreport-electron-pdf` i have customized the name to `JSREPORT_READY_TO_START`](https://github.com/bjrmatos/jsreport-electron-pdf/blob/master/src/recipe.js#L33), i think this name is more generic and does not asume that it only be used to generate PDF, in the end the `waitForJS` feature is generic enough to be used in any recipe (images, etc)

**Comment by pofider** [comment]
Ok, this makes switching between recipes easier. I guess this feature is anyway not yet used, so lets do it.

**Comment by bjrmatos** [comment]
:+1: i think i'm the only person taking advange of it :laughing:

**Comment by pofider** [comment]
It makes more sense at least for images. Thanks for good suggestion!
