### ISSUE TITLE
run template to pdf error

### ISSUE THREAD

**Issue by jdevsean** [jsreport/jsreport-phantom-pdf#16]
hi sir , i already install phantom-pdf . when i create a simple template ,engine is handlebars and recipe is phantom-pdf , is failed . the console's err message is 
![1489596539 1](https://cloud.githubusercontent.com/assets/26438287/23960244/62f41500-09e2-11e7-8718-408abb04e500.png)
and then , i input npm bugs jsreport-server ,the err is 'jsreport-server' is not in the npm registry.
please . thanks!

**Comment by bjrmatos** [comment]
hi! can you upload the full log? you should have a `npm-debug.log` file in your current working directory with all the logs. also, what OS are you using (linux, windows, osx)? 

other question, how are you using `jsreport-phantom-pdf`? are you installing it manually? just note that if you are using the `jsreport` package, jsreport-phantom-pdf is installed by default.

**Comment by jdevsean** [comment]
ok,i use linux OS , i find it that the jsreport-pantom-pdf is already intsll by default . thank, the log is that

[npm-debug.txt](https://github.com/jsreport/jsreport-phantom-pdf/files/845473/npm-debug.txt)

thanks!

**Comment by bjrmatos** [comment]
hmm unfortunately the logs doesn't have any useful information.. can you try to run `node server.js` and show me what you get in the console?

**Comment by jdevsean** [comment]
ok ! 

![1489599482 1](https://cloud.githubusercontent.com/assets/26438287/23962790/36771a06-09ea-11e7-823d-b9ab08094b59.png)

**Comment by jdevsean** [comment]
my template just a very simple template , no script ,no data 
![1489600102 1](https://cloud.githubusercontent.com/assets/26438287/23962947/b282af20-09ea-11e7-9dc9-9d307e555047.png)

**Comment by bjrmatos** [comment]
same error with `node server`, right? hmm could it be a permission issue in linux? i see that you are using `/root` as your project directory maybe you can try to move the project to another location, probably your home directory and see if you have the same error there.

**Comment by jdevsean** [comment]
unfortunately , the error still exit , i think that maybe the npm has some problem .

**Comment by bjrmatos** [comment]
ok, just note that when using `phantomjs` on linux you need to install some additionally packages, see this instructions -> https://gist.github.com/julionc/7476620

**Comment by bjrmatos** [comment]
try to run this:

```
sudo apt-get update
sudo apt-get install build-essential chrpath libssl-dev libxft-dev

sudo apt-get install libfreetype6 libfreetype6-dev
sudo apt-get install libfontconfig1 libfontconfig1-dev
```

**Comment by jdevsean** [comment]
ok , i will try , but i maybe tell you the result in tommorow  , because now is 2.25 in china . thanks for your help!

**Comment by jdevsean** [comment]
my OS is centOS , some  soft install failed;

**Comment by bjrmatos** [comment]
oh sorry for didn't ask your linux distribution first.. try this: `sudo yum install freetype fontconfig`

**Comment by jdevsean** [comment]
hi sir , i run it , the result is already is latest version;

**Comment by bjrmatos** [comment]
to confirm.. does it work now? can you render pdf without problems?

**Comment by jdevsean** [comment]
unfortunately ， the issue still exit , if i render pdf by wkhtmlpdf , it without any problems.

i remenber that when i install jsreport by command line , stay for a while in the receiving state , so i finish it , and install try again , i know there is loss a zip file in my inpression .

**Comment by bjrmatos** [comment]
hmm ok, you can try reinstalling and if it doesn't work.. can you start jsreport with `node server.js`, start pdf rendering and send me the result of your console? if there is an error you will have more details now because you won't be using `npm start`

**Comment by bjrmatos** [comment]
ah yes, make sure that when installing you have the appropriate permissions because the decompression of the phantomjs zip file can fail because of that, and just for test you can try installing with `sudo npm install` just to see if there is some kind of permission issue

**Comment by jdevsean** [comment]
ok ! i will try to reinstalling again , and will note the situation from install to start , if the error still happen , i will give you more detail ! 
thanks~~

**Comment by bjrmatos** [comment]
ok, thnks, just a note, i made a mistake the command should be `sudo npm install jsreport`
