### ISSUE TITLE
Phantomjs 2.1.1 did not appear on template combobox

### ISSUE THREAD

**Issue by NghiaHanoi** [jsreport/jsreport-phantom-pdf#23]
On MacOS Sierra, when editing report using jsreport studio I follow the guide from https://jsreport.net/learn/phantom-pdf#macos-sierra for fixing the issue with phantom 1.9.8.
I have already upgrade phantom to 2.1.1 for my system phantom -v -> "2.1.1".
When restart jsreport and editing template, in the phantomjs property combobox I just can see only version 1.9.8?! cannot choose 2.1.1
Please help!

**Comment by NghiaHanoi** [comment]
Ah, sorry, it is done now after updating OS System with newest update

**Comment by pofider** [comment]
Ok. Thanks. So I guess I can close this now.
