### ISSUE TITLE
Why background-color missing

### ISSUE THREAD

**Issue by taoqf** [jsreport/jsreport-phantom-pdf#26]
I find there is a setting called `background graphics` in chrome when I print a page.
How could I do in jsreport?

**Comment by pofider** [comment]
This recipe is using phantomjs. Aren't you in a wrong repository here?

**Comment by taoqf** [comment]
After I remove bootstrap from html, this issue is gone, though i don't know why. thanks anyway.

**Comment by pofider** [comment]
FYI the explanation is in the docs.
https://jsreport.net/learn/phantom-pdf#twitter-bootstrap

**Comment by taoqf** [comment]
thanks.
