### ISSUE TITLE
node v12

### ISSUE THREAD

**Issue by taoqf** [jsreport/jsreport-phantom-pdf#36]
It just doesn't work, maybe it's because of [phantom-html-to-pdf](https://www.npmjs.com/package/phantom-html-to-pdf), seems not maintained for a long time.

**Comment by pofider** [comment]
https://github.com/jsreport/jsreport-phantom-pdf/issues/35

Please downgrade to the LTS version - node 10.
Until will we fix what is wrong with node 12.

**Comment by taoqf** [comment]
node v10 and v11 both will do.

**Comment by bjrmatos** [comment]
i will close this in favor of jsreport/jsreport#578, follow that issue for updates
