### ISSUE TITLE
Unicode Characters (eg. Ω)

### ISSUE THREAD

**Issue by metachris** [jsreport/jsreport-phantom-pdf#5]
The "National characters" example from http://jsreport.net/learn/phantom-pdf works, but unicode characters such as the Ohm symbol (Ω) are not rendered in the pdf. The handlebars engine with html output renders the symbol correctly.

Edit: Perhaps related to https://github.com/marcbachmann/node-html-pdf/issues/20

**Comment by pofider** [comment]
It works on windows: https://playground.jsreport.net/studio/workspace/S13dQsS4/3

So maybe it is about some missing fonts installed on the server.

**Comment by metachris** [comment]
It renders on the server side, so I suppose it means that on the rendering server of playground.jsreport.net the fonts are installed, but on my server not.

Is there a full tutorial somewhere (what is the default font, and which font packages need to be installed on the system)?

**Comment by pofider** [comment]
There are some fontconfig and libfontconfig mentioned for linux in the phantomjs docs http://phantomjs.org/download.html

**Comment by metachris** [comment]
Was related to this issue: https://github.com/ariya/phantomjs/issues/13464

Actual Solution: `yum install cjkuni-fonts-common cjkuni-ukai-fonts cjkuni-uming-fonts`

**Comment by Vunb** [comment]
For Microsoft TrueType Fonts, i found the link [How to install Microsoft TrueType Fonts in CentOS 6 / RHEL 6](http://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-install-microsoft-truetype-fonts-in-centos-6-rhel-6.html)
