### ISSUE TITLE
Use phantom 2

### ISSUE THREAD

**Issue by postama** [jsreport/jsreport-phantom-pdf#8]
With the macOS Sierra upgrade, phantom 1 is not working. How can we use this package with phantom 2.x?

**Comment by pofider** [comment]
1.`npm install phantomjs-prebuilt`
2. render report with 
```js
{
  template: {
    phantom: {
      customPhantomJS: true
    }
  }
}
```

**Comment by JonathanWilkins** [comment]
Is there a way to do this globally for the instance of jsreport server as apposed to per template

**Comment by pofider** [comment]
This can be done using custom script

```js
function beforeRender(req, res, done) {
   if (req.template.recipe === 'phantom-pdf') {
     req.template.phantom =  req.template.phantom || {}
     req.template.phantom.customPhantomJS = true
  }
  done()
}
```

Mark it as global in studio and it will do the job for all templates.

**Comment by pofider** [comment]
jsreport-phantom-pdf@1.3.0 now has global setting for this

```js
"phantom": {   
    "defaultPhantomjsVersion": "2.1.1"
  }
```

The macOs sierra problem is also noted in the docs now
http://jsreport.net/learn/phantom-pdf#macos-sierra

**Comment by NghiaHanoi** [comment]
On MacOS Sierra, when editing report using jsreport studio I follow the guide from https://jsreport.net/learn/phantom-pdf#macos-sierra for fixing the issue with phantom 1.9.8.
I have already upgrade phantom to 2.1.1 for my system phantom -v -> "2.1.1".
When restart jsreport and editing template, in the phantomjs property combobox I just can see only version 1.9.8?! cannot choose 2.1.1
